name: Track Real Estate Ads

on:
  schedule:
    - cron: '0 7 * * *'  # Run at 7 AM UTC
  workflow_dispatch:  

permissions:
  contents: write  # Allow write access to repository

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in GITHUB_TOKEN
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Send Telegram Notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=HTML \
            --data-urlencode "text=$(cat telegram-message.txt)"
        
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/ reports/ price-history.json
          git commit -m "Daily update $(date '+%Y-%m-%d')" || echo "No changes to commit"
          git push